import paramiko, json
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect('158.255.4.142', username='root', password='Kostaden2312-')
stdin, stdout, stderr = client.exec_command('docker inspect safescan-caddy')
data = json.loads(stdout.read().decode('utf-8', errors='replace'))[0]
config = data.get('Config', {})
host_config = data.get('HostConfig', {})
print('Image:', config.get('Image'))
print('Cmd:', config.get('Cmd'))
print('Entrypoint:', config.get('Entrypoint'))
print('Env:', config.get('Env'))
print('Volumes:', host_config.get('Binds'))
print('PortBindings:', host_config.get('PortBindings'))
print('NetworkMode:', host_config.get('NetworkMode'))
print('RestartPolicy:', host_config.get('RestartPolicy'))
client.close()
